### ISSUE TITLE
tuic-server 0.22 x86_64 在 debian bullseye 版本运行报错

### ISSUE THREAD

**Issue by wchen9** [EAimTY/tuic#10]
```bash
luis@bwg:~/tuic$ export RUST_BACKTRACE=full
luis@bwg:~/tuic$ ./tuic-server-0.2.2-x86_64-linux-gnu -p 16385 -t abbb -c fullchain.pem -k privkey.pem --congestion-controller bbr
thread 'main' panicked at 'internal error: entered unreachable code', server/src/server.rs:53:31
stack backtrace:
   0:     0x5600882a9755 - <unknown>
   1:     0x5600881ca44c - <unknown>
   2:     0x560088286374 - <unknown>
   3:     0x5600882aa43e - <unknown>
   4:     0x5600882ab2f2 - <unknown>
   5:     0x5600882aacf8 - <unknown>
   6:     0x5600882aac96 - <unknown>
   7:     0x5600882aac52 - <unknown>
   8:     0x560088187dd0 - <unknown>
   9:     0x560088187f2c - <unknown>
  10:     0x5600881a7a43 - <unknown>
  11:     0x56008819e52f - <unknown>
  12:     0x5600881c0d23 - <unknown>
  13:     0x5600881c5b3c - <unknown>
  14:     0x7f7336c25d0a - __libc_start_main
  15:     0x560088192d7e - <unknown>
  16:                0x0 - <unknown>
```

0.21 版本无此问题。

**Comment by molezz** [comment]
gnu musl一致的情况，ubuntu
```
root@zz:~# /root/tuic-server-0.2.2-x86_64-linux-musl -p 3643 -t cell23D -c .acme.sh/certificate.crt -k .acme.sh/cf.key --congestion-controller bbr
thread 'main' panicked at 'internal error: entered unreachable code', server/src/server.rs:53:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

root@zz:~# uname -a
Linux zz 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by EAimTY** [comment]
抱歉犯了低级错误，已经在 0.2.3 中修复了
